<?php

/**
 * Register ACF Fields for Wines Post Type
 */
function meiomi_register_wines_field_group()
{
	if (function_exists('acf_add_local_field_group')):
		acf_add_local_field_group([
			'key' => 'group_wines',
			'title' => 'Wine Details',
			'fields' => [
				[
					'key' => 'field_wine_points_image',
					'label' => 'Points Image',
					'name' => 'points_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'Upload the wine points image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '50',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'thumbnail',
				],
				[
					'key' => 'field_wine_bottle_image',
					'label' => 'Bottle Image',
					'name' => 'bottle_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'Upload the wine bottle image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '50',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'id',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'thumbnail',
				],
				[
					'key' => 'field_wine_title',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Wine title (if different from post title)',
				],
				[
					'key' => 'field_wine_location',
					'label' => 'Location',
					'name' => 'location',
					'type' => 'text',
					'instructions' => 'Wine location/region',
				],
				[
					'key' => 'field_wine_description',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'wysiwyg',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				],
				[
					'key' => 'field_wine_color_picker',
					'label' => 'Color Picker',
					'name' => 'color_picker',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'allow_in_bindings' => 0,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				],
				[
					'key' => 'field_wine_shop_link',
					'label' => 'Shop Link',
					'name' => 'shop_link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => 'Select a page to link to for purchasing this wine',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'return_format' => 'array',
					'allow_in_bindings' => 0,
				],
				[
					'key' => 'field_wine_upc',
					'label' => 'UPC Code',
					'name' => 'upc_code',
					'type' => 'text',
					'instructions' => 'UPC code for this wine (used for MikMak store locator)',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '50',
						'class' => '',
						'id' => '',
					],
				],
				[
					'key' => 'field_wine_varietals',
					'label' => 'Varietals',
					'name' => 'varietals',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Varietal',
					'rows_per_page' => 20,
					'sub_fields' => [
						[
							'key' => 'field_soze',
							'label' => 'Size',
							'name' => 'size',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'choices' => [
								'187ml' => '187ml',
								'500ml' => '500ml',
								'750ml' => '750ml',
								'1-5L' => '1.5L',
								'3L' => '3L',
							],
							'default_value' => '187ml',
							'return_format' => 'array',
							'allow_null' => 0,
							'other_choice' => 0,
							'allow_in_bindings' => 0,
							'layout' => 'horizontal',
							'save_other_choice' => 0,
							'parent_repeater' => 'field_wine_varietals',
						],
						[
							'key' => 'field_image',
							'label' => 'Image',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'thumbnail',
							'parent_repeater' => 'field_wine_varietals',
						],
					],
				],
				[
					'key' => 'field_brand_logos',
					'label' => 'Brand Logos',
					'name' => 'brand_logo',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
						'width' => '',
						'class' => '',
						'id' => '',
					],
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Logo',
					'rows_per_page' => 20,
					'sub_fields' => [
						[
							'key' => 'field_logo',
							'label' => 'Logo',
							'name' => 'logo',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'return_format' => 'id',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'thumbnail',
							'parent_repeater' => 'field_brand_logos',
						],
					],
				],
				[
					'key' => 'field_wine_description_headline',
					'label' => 'Headline',
					'name' => 'description_headline',
					'type' => 'text',
					'instructions' => '',
				],
				[
					'key' => 'field_wine_description_description',
					'label' => 'Description',
					'name' => 'description_description',
					'type' => 'wysiwyg',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				],



			],
			'location' => [
				[
					[
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'wine',
					],
				],
			],
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'seamless',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => 'Fields for wine post type',
		]);
	endif;
}
add_action('acf/init', 'meiomi_register_wines_field_group');
